# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftSeedProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftSeedProject

  pod 'Dip', '5.0.4'
  pod 'Dip-UI', '1.0.2'
  pod 'Bond', '6.2.4'
  pod 'Alamofire', '4.4'
  pod 'SwiftyJSON', '3.1.4'
  pod 'SDWebImage', '4.0.0'

end
